# NOTE: update this with your service name
# Name of the stack created by serverless framework. If you change the name and
# deploy your proyect, it willl create a completely new project
service: notes-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  # write lambda functions using ECMAScript
  - serverless-bundle # Package our functions with Webpack
  # for local development
  - serverless-offline
  # load the .env files as Lambda environment variables
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

# lambda functions
functions:
  hello:
    # handler: {filename}-{export}
    handler: handler.hello
    events:
      # responds to and HTTP GET event with the path /hello
      - http:
          path: hello
          method: get
